services:
  northwind_db:
    image: postgres:13
    environment:
      - POSTGRES_USER=northwind
      - POSTGRES_PASSWORD=northwind_password
      - POSTGRES_DB=NorthwindDb
    volumes:
      - "/Users/berkkayi/Desktop/northwind/northwind_volume:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
    networks:
      - pg-network
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8081:80"
    networks:
      - pg-network
networks:
  pg-network: